# The Waveshare ESP32-P4-WIFI6-Touch-LCD-7B is a self contained, 7 inch 1024x600 touchscreen display with an ESP32-P4 MCU.
# It has an ESP32-C6 co-processor that gives the P4 Wi-Fi capabilities.
# 
# Schematic: https://files.waveshare.com/wiki/ESP32-P4-WIFI6-Touch-LCD-7B/ESP32-P4-WIFI6-Touch-LCD-7B.pdf

esphome:
  name: waveshare-esp32-p4-wifi6-touch-lcd-7b
  friendly_name: waveshare-esp32-p4-wifi6-touch-lcd-7b

esp32:
  variant: esp32p4
  flash_size: 16MB
  cpu_frequency: 360MHz
  framework:
    type: esp-idf
    advanced:
      enable_idf_experimental_features: true

esp32_hosted:
  variant: ESP32C6
  reset_pin: GPIO54
  cmd_pin: GPIO19
  clk_pin: GPIO18
  d0_pin: GPIO14
  d1_pin: GPIO15
  d2_pin: GPIO16
  d3_pin: GPIO17
  active_high: true

logger:
  hardware_uart: USB_SERIAL_JTAG

psram:
  mode: hex
  speed: 200MHz

i2c:
  - id: bsp_bus
    sda: GPIO07
    scl: GPIO08
    frequency: 400kHz
    
touchscreen:
  - platform: gt911
    id: touch
    #interrupt_pin: # It's on TouchPoint1, you would have to manually jumper it to a GPIO pin.
    reset_pin:
      number: 23
    update_interval: never
    calibration:
      x_min: 0
      x_max: 600
      y_min: 0
      y_max: 1024

esp_ldo:
  - voltage: 2.5V
    channel: 3

display:
  - platform: mipi_dsi
    dimensions:
      height: 1024
      width: 600
    model: WAVESHARE-ESP32-P4-WIFI6-TOUCH-LCD-7B
    show_test_card: true

output:
  - platform: ledc
    pin: GPIO32
    id: backlight_pwm
    frequency: 1000Hz

light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Backlight"
    id: backlight
    restore_mode: RESTORE_DEFAULT_ON
    default_transition_length: 250ms

lvgl:
  byte_order: little_endian
